// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsuppbtbvlkxoxdjmqwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzdXBwYnRidmxreG94ZGptcXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MTg2NTAsImV4cCI6MjA3MDM5NDY1MH0.3QZ_mIozCsU2VGaSE21cSTwQbD-Qg9orZeeetfpGZ5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});